In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('SuperMarket.csv')

In [3]:
# Data Profiling Phase
df.shape

(1014, 17)

In [4]:
df.dtypes

Invoice ID                     str
Branch                         str
City                           str
   Customer type               str
Gender                         str
Product line                   str
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                          str
Date                           str
Time                           str
Payment                        str
   cogs                    float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [5]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
   Customer type            0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
   cogs                     0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(14)

In [7]:
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,55.520333,5.502959,15.336872,306.737436,4.761905,15.336872,6.960454
std,26.330508,2.927133,11.685945,233.718896,0.000000,11.685945,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905,49.650000,10.000000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   str
 1   Branch                   1014 non-null   str
 2   City                     1014 non-null   str
 3      Customer type         1014 non-null   str
 4   Gender                   1014 non-null   str
 5   Product line             1014 non-null   str
 6   Unit price               990 non-null    float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    str
 10  Date                     1002 non-null   str
 11  Time                     1014 non-null   str
 12  Payment                  1014 non-null   str
 13     cogs                  1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), str(10)
memory usage: 134.8 KB

In [9]:
# Identify any suspicious data.
df[df["Quantity"] <= 0]
df[df["Unit price"] <= 0]
df[df["Tax 5%"] <= 0]
df[df["   cogs"] <= 0]

Empty DataFrame
Columns: [Invoice ID, Branch, City,    Customer type, Gender, Product line, Unit price, Quantity, Tax 5%, Sales, Date, Time, Payment    ,    cogs, gross margin percentage, gross income, Rating]
Index: []

In [10]:
df[(df["Rating"] < 0) | (df["Rating"] > 10)]

Empty DataFrame
Columns: [Invoice ID, Branch, City,    Customer type, Gender, Product line, Unit price, Quantity, Tax 5%, Sales, Date, Time, Payment    ,    cogs, gross margin percentage, gross income, Rating]
Index: []

In [11]:
# Data Cleaning Phase
df.columns

Index(['Invoice ID', 'Branch', 'City', '   Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment    ', '   cogs', 'gross margin percentage',
       'gross income', 'Rating'],
      dtype='str')

In [12]:
# Rename Columns
df = df.rename (columns = {'   Customer type' : 'Customer type', '   cogs' : 'COGS','Payment    ':'Payment'} )

In [13]:
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['Invoice_ID', 'Branch', 'City', 'Customer_type', 'Gender',
       'Product_line', 'Unit_price', 'Quantity', 'Tax_5%', 'Sales', 'Date',
       'Time', 'Payment', 'COGS', 'gross_margin_percentage', 'gross_income',
       'Rating'],
      dtype='str')

In [14]:
# Change data type 
df['Invoice_ID'] = df['Invoice_ID'].str.replace('-', '')
df['Invoice_ID'] = df['Invoice_ID'].astype('int64')

In [15]:
df['Invoice_ID'].dtype

dtype('int64')

In [16]:
df['Sales'] = df['Sales'].str.replace('EGP', '')
df['Sales'] = df['Sales'].astype('float64')

In [17]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [18]:
# Making sure all columns have the correct data types
df.dtypes

Invoice_ID                          int64
Branch                                str
City                                  str
Customer_type                         str
Gender                                str
Product_line                          str
Unit_price                        float64
Quantity                            int64
Tax_5%                            float64
Sales                             float64
Date                       datetime64[us]
Time                                  str
Payment                               str
COGS                              float64
gross_margin_percentage           float64
gross_income                      float64
Rating                            float64
dtype: object

In [19]:
# Handling Missing Values
df['Unit_price'] = df['Unit_price'].fillna(((df['Sales'] - df['Tax_5%']) / df['Quantity']))

In [20]:
df['Sales'] = df['Sales'].fillna((df['Unit_price'] * df['Quantity']) + df['Tax_5%'])

In [21]:
df['Date'] = df['Date'].fillna("2020-01-01")

In [22]:
# Check Duplicates
df.duplicated().sum()

np.int64(14)

In [23]:
df = df.drop_duplicates()

In [24]:
# Remove Unnecessary columns
df = df.drop (
    columns=[
        "Gender",
        "Unit_price",
        "Quantity",
        "Tax_5%",
        "Time",
        "gross_margin_percentage",
        "COGS"
    ]
)

In [25]:
df['Branch'].value_counts()

Branch
Alex                  337
Giza                  327
Cairo                 326
     Cairo              4
Alex                    3
giza                    1
cairo                   1
      Cairo             1
Name: count, dtype: int64

In [26]:
df['Branch'] = df['Branch'].str.strip().replace({'giza':'Giza','cairo':'Cairo'})

In [27]:
df['City'].value_counts()

City
Yangon       340
Mandalay     332
Naypyitaw    328
Name: count, dtype: int64

In [28]:
df['Customer_type'].value_counts()

Customer_type
Member    565
Normal    435
Name: count, dtype: int64

In [29]:
df['Product_line'].value_counts()

Product_line
Fashion accessories       178
Food and beverages        174
Electronic accessories    170
Sports and travel         166
Home and lifestyle        160
Health and beauty         152
Name: count, dtype: int64

In [30]:
df['Payment'].value_counts()

Payment
Ewallet        341
Cash           337
Credit card    306
cash             7
credit card      5
E-wallet         4
Name: count, dtype: int64

In [31]:
df['Payment'] = df['Payment'].replace({'cash':'Cash','credit card':'Credit card', 'E-wallet':'Ewallet'})

In [32]:
# Sort data by date
df = df.sort_values('Date')

In [33]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [34]:
# Creating Satisfiction Column
def check_satisfiction(rating):
    if rating >= 7:
      return 'Satisfied'
    else: 
       return 'Not Satisfied'

In [35]:
df['Satisfied'] = df['Rating'].apply(check_satisfiction)

In [36]:
df.to_csv("SuperMarket_Cleaned.csv", index=False)